version: '3'

services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: viajesparatidb
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  mailer:
    image: schickling/mailcatcher
    ports:
      - "58048:1025"
      - "58047:1080"

volumes:
  db_data: