version: '3'

services:
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: viajesparatidb
    image: mysql
###< doctrine/doctrine-bundle ###
